---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: playbook.yml
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_version: latest
  require_chef_for_busser: false
  require_ruby_for_busser: true
  # requirements_path: requirements.txt
  ansible_extra_flags: "--tags 'install'"

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
# Alternatively for RVM
# which ruby
# ~/.rvm/rubies/ruby-2.2.0/bin/ruby
verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: default
    run_list:
    attributes:
