---
# tasks file for ansible-mono

- name:  Add an rpm keyserver
  command: rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
  tags:
     - install

- name: Add the mono repository for Centos
  yumrepo:
    name: mono-centos
    description: Mono Centos repo
    baseurl: http://download.mono-project.com/repo/centos/
  tags:
     - install

- name: Install Mono dependencies
  yum: pkg={{ item }} state=installed
  with_items:
     - mono-devel
     - mono-complet
     - referenceassemblies-pcl
     - ca-certificates-mono
  tags:
     - install
